name: MLflow CI Training

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-name: mlflow-env
        create-args: >-
          python=3.12
          pip
        init-shell: bash

    - name: Install dependencies via pip
      shell: bash
      run: |
        micromamba activate mlflow-env
        pip install mlflow==2.19.0 pandas scikit-learn

    - name: Run MLflow Project (conda)
      shell: bash
      run: |
        micromamba activate mlflow-env
        mlflow run MLProject \
          --env-manager=conda \
          -P input_path=MLProject/coffeshop_preprocessing.csv
